[package]
name = "http_server"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
# actix-web = "1.0.3"
hyper = { version = "0.12", default-features = false, features = ["runtime"] }
tokio-threadpool = "0.1.13"
tokio-fs = "0.1.6"
tokio-io = "0.1.12"
futures = "0.1"
futures-locks = "0.1"
url = "1.7.2"
tempfile = "3.0"
lazy_static = "1.3"
mime = "0.3.13"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
fail = "0.2"
quick-error = "1.2.2"

tikv_alloc = { path = "../tikv_alloc", default-features = false }
tikv_util = { path = "../tikv_util" }

slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "91904ade" }
